<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MunicipalitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * Seeds the municipalities of Bukidnon Province, Region X (Northern Mindanao)
     */
    public function run(): void
    {
        $municipalities = [
            // Cities
            [
                'name' => 'Valencia City',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8709',
                'latitude' => 7.9089,
                'longitude' => 125.0942,
                'population' => 216546,
                'land_area_sqkm' => 621.00,
                'contact_number' => '(088) 828-1234',
                'email' => 'valencia.mdrrmo@bukidnon.gov.ph',
                'address' => 'Valencia City Hall, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Malaybalay City',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8700',
                'latitude' => 8.1535,
                'longitude' => 125.1275,
                'population' => 190712,
                'land_area_sqkm' => 969.18,
                'contact_number' => '(088) 221-1234',
                'email' => 'malaybalay.mdrrmo@bukidnon.gov.ph',
                'address' => 'Malaybalay City Hall, Bukidnon',
                'is_active' => true,
            ],
            // Municipalities
            [
                'name' => 'Manolo Fortich',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8703',
                'latitude' => 8.3667,
                'longitude' => 124.8667,
                'population' => 113200,
                'land_area_sqkm' => 383.19,
                'contact_number' => null,
                'email' => 'manolofortich.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Manolo Fortich, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Baungon',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8712',
                'latitude' => 8.2667,
                'longitude' => 124.7333,
                'population' => 35111,
                'land_area_sqkm' => 196.30,
                'contact_number' => null,
                'email' => 'baungon.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Baungon, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Cabanglasan',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8714',
                'latitude' => 7.5833,
                'longitude' => 125.3833,
                'population' => 67219,
                'land_area_sqkm' => 659.68,
                'contact_number' => null,
                'email' => 'cabanglasan.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Cabanglasan, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Damulog',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8715',
                'latitude' => 7.4833,
                'longitude' => 124.9500,
                'population' => 26898,
                'land_area_sqkm' => 205.10,
                'contact_number' => null,
                'email' => 'damulog.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Damulog, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Impasugong',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8702',
                'latitude' => 8.3000,
                'longitude' => 125.0000,
                'population' => 51587,
                'land_area_sqkm' => 366.00,
                'contact_number' => null,
                'email' => 'impasugong.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Impasugong, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Kalilangan',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8716',
                'latitude' => 7.7000,
                'longitude' => 124.5000,
                'population' => 42988,
                'land_area_sqkm' => 292.20,
                'contact_number' => null,
                'email' => 'kalilangan.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Kalilangan, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Lantapan',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8722',
                'latitude' => 7.9833,
                'longitude' => 125.0333,
                'population' => 66081,
                'land_area_sqkm' => 324.05,
                'contact_number' => null,
                'email' => 'lantapan.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Lantapan, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Libona',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8720',
                'latitude' => 8.3333,
                'longitude' => 124.7500,
                'population' => 45676,
                'land_area_sqkm' => 232.00,
                'contact_number' => null,
                'email' => 'libona.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Libona, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Quezon',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8725',
                'latitude' => 7.7333,
                'longitude' => 125.1000,
                'population' => 109624,
                'land_area_sqkm' => 487.70,
                'contact_number' => null,
                'email' => 'quezon.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Quezon, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'San Fernando',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8726',
                'latitude' => 7.9167,
                'longitude' => 125.3167,
                'population' => 63045,
                'land_area_sqkm' => 550.00,
                'contact_number' => null,
                'email' => 'sanfernando.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, San Fernando, Bukidnon',
                'is_active' => true,
            ],
            [
                'name' => 'Talakag',
                'province' => 'Bukidnon',
                'region' => 'Region X',
                'zip_code' => '8704',
                'latitude' => 8.2333,
                'longitude' => 124.6000,
                'population' => 73292,
                'land_area_sqkm' => 713.80,
                'contact_number' => null,
                'email' => 'talakag.mdrrmo@bukidnon.gov.ph',
                'address' => 'Municipal Hall, Talakag, Bukidnon',
                'is_active' => true,
            ],
        ];

        foreach ($municipalities as $municipality) {
            DB::table('municipalities')->insert(array_merge($municipality, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
