<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Bukidnon Municipalities and Barangays
    |--------------------------------------------------------------------------
    |
    | This configuration file contains all municipalities in Bukidnon
    | and their respective barangays for the incident reporting system.
    |
    */

    'municipalities' => [
        'Baungon' => [
            'Barangay 1 (Pob.)',
            'Barangay 2 (Pob.)',
            'Barangay 3 (Pob.)',
            'Balintad',
            'Buenavista',
            'Danatag',
            'Kalilangan',
            'Liboran',
            'Lingating',
            'Mabuhay',
            'Mabunga',
            'Nicdao',
            'Pualas',
            'Salimbalan',
            'San Miguel',
            'Sanipon',
            'Sto. Niño',
        ],
        'Cabanglasan' => [
            'Barangay 1 (Pob.)',
            'Barangay 2 (Pob.)',
            'Barangay 3 (Pob.)',
            'Barangay 4 (Pob.)',
            'Mandaing',
            'Mauswagon',
            'Salucot',
            'Santiago',
        ],
        'Damulog' => [
            'Aludas',
            'Angga-an',
            'Balangigay',
            'Cebole',
            'Dagumbaan',
            'Kalilangan',
            'Kauyonan',
            'Kinapat',
            'Kiraon',
            'Kitingting',
            'Lagandang',
            'Lamagos',
            'Macapaya',
            'Magsaysay',
            'Maitum',
            'Omonay',
            'Poblacion',
            'Poloyagan',
            'Samples',
            'San Isidro',
            'Tangkulan',
        ],
        'Dangcagan' => [
            'Durian',
            ' Intercol',
            'Kapayas',
            'Kibatang',
            'Lourdes',
            'Miarayon',
            'New Visayas',
            'Paco',
            'Paradise',
            'Poblacion',
            'San Isidro',
            'Tugop',
            'Upper Danggawan',
        ],
        'Don Carlos' => [
            'Poblacion',
            'Bukidnon',
            'Cabadiangan',
            'Cagawasan',
            'Colawingon',
            'Embayao',
            'Kalubihon',
            'Kasigkot',
            'Kawilihan',
            'Kiara',
            'Kitulaan',
            'Mabuhay',
            'Manlamonay',
            'Maraymaray',
            'New Nongnongan',
            'Old Nongnongan',
            'Pinamaloy',
            'San Antonio',
            'San Francisco',
            'San Luis',
            'San Roque',
            'Sinuda',
        ],
        'Impasugong' => [
            'Bongbong',
            'Bulonay',
            'Cawayan',
            'Guihean',
            'Hagpa',
            'Impalambong',
            'Impalutao',
            'Kalabugao',
            'Kibenton',
            'La Fortuna',
            'Laguitas',
            'Lian',
            'Licoan',
            'Lumbo',
            'Mabanban',
            'Poblacion',
            'Sayawan',
            'Sto. Niño',
            'Dumalaguing',
        ],
        'Kadingilan' => [
            'Bagongbayan',
            'Bangahan',
            'Baroy',
            'Beyabagaan',
            'Biasong',
            'Cabalantian',
            'Cabangahan',
            'Chanarian',
            'Kiliog',
            'Kitobo',
            'Lower Olave',
            'Mabuhay',
            'Malinao',
            'Matampay',
            'New Antique',
            'Old Damulog',
            'Panganan',
            'Poblacion',
            'Salvacion',
            'San Antonio',
            'San Isidro',
            'Sibonga',
            'Sinuda',
            'Upper Olave',
        ],
        'Kalilangan' => [
            'Bangbang',
            'Cabulohan',
            'Concepcion',
            'Dahilayan',
            'Dologon',
            'Dumalaguing',
            'Guilang-guilang',
            'Kabalabag',
            'Kabalukan',
            'Keboan',
            'Kibonbon',
            'Kipalili',
            'Kisolon',
            'Lico-an',
            'Lingion',
            'Mabuhay',
            'Poblacion',
            'Santiago',
            'Sayaton',
            'Tabialan',
        ],
        'Kibawe' => [
            'Balintawak',
            'Cabulohan',
            'Cananaman',
            'Cibalabag',
            'Dagundalahon',
            'Kiorao',
            'Kisawa',
            'Labuagon',
            'Magsaysay',
            'Matupe',
            'New Kidapawan',
            'Pagalungan',
            'Pinamaloy',
            'Poblacion',
            'Romagooc',
            'Sampagar',
            'San Vicente',
            'Simbalan',
            'Spring',
            'Sto. Niño',
            'Talahiron',
        ],
        'Kitaotao' => [
            'Bagumbayan',
            'Balangigay',
            'Bangahan',
            'Capitan Bayong',
            'Cabadiangan',
            'Dalwangan',
            'Kisanday',
            'Lunocan',
            'Magsaysay',
            'New Cebu',
            'Old Damulog',
            'Palma',
            'Poblacion',
            'San Isidro',
            'San Roque',
            'Santo Niño',
            'Sinuda',
            'Tandong',
        ],
        'Lantapan' => [
            'Balila',
            'Bantuanon',
            'Bugcaon',
            'Capitan Juan',
            'Culasi',
            'Kabalabag',
            'Kapatagan',
            'Kibangay',
            'Mambatangan',
            'Poblacion',
            'Sanctuary',
            'Santo Niño',
            'Songco',
            'Victory',
        ],
        'Libona' => [
            'Cabangahan',
            'Crossing',
            'Del Monte',
            'Katipunan',
            'Kinawe',
            'Kisolon',
            'Kiyaab',
            'Maambong',
            'Maasin',
            'Poblacion',
            'Pongol',
            'San Antonio',
        ],
        'Malitbog' => [
            'Alanib',
            'Barongcot',
            'Buenavista',
            'Cabangahan',
            'Caburacanan',
            'Camp 1',
            'Capitan Angel',
            'Dalurong',
            'Dologon',
            'Iba',
            'Kalumihan',
            'Kibogtok',
            'Lamazon',
            'Lampanusan',
            'Lapok',
            'Magsaysay',
            'Malitubog',
            'Managok',
            'Metebagao',
            'Poblacion',
            'San Isidro',
            'San Jose',
            'Santo Niño',
            'Sinanglanan',
            'Tawas',
        ],
        'Manolo Fortich' => [
            'Agusan Canyon',
            'Alae',
            'Dahilayan',
            'Dalirig',
            'Diclum',
            'Guilang-guilang',
            'Kalilangan',
            'Kibalas',
            'Kibangay',
            'Lingion',
            'Lunocan',
            'Maluko',
            'Mambatangan',
            'Minsuro',
            'Poblacion',
            'San Miguel',
            'Sankanan',
            'Sto. Niño',
            'Tankulan',
        ],
        'Maramag' => [
            'Aglayan',
            'Bagongsilangan',
            'Barangay 1 (Pob.)',
            'Barangay 2 (Pob.)',
            'Barangay 3 (Pob.)',
            'Barangay 4 (Pob.)',
            'Barangay 5 (Pob.)',
            'Barangay 6 (Pob.)',
            'Barangay 7 (Pob.)',
            'Barangay 8 (Pob.)',
            'Basiawan',
            'Bolo',
            'Bugwak',
            'Bulonay',
            'Camp I',
            'Dagumbaan',
            'Danggawan',
            'Dologon',
            'Gumabon',
            'Kabalantian',
            'Kuya',
            'Laguitas',
            'Lampanusan',
            'La Roxas',
            'Leuteboro',
            'Mahayahay',
            'Malinao',
            'Mauswagon',
            'Minsalay',
            'Panadtaban',
            'San Roque',
            'Sto. Niño',
            'Tubigon',
        ],
        'Pangantucan' => [
            'Barandias',
            'Dagundalahon',
            'Ganatan',
            'Junction',
            'Kahusayan',
            'Kasikalan',
            'Kibatang',
            'Kibalagon',
            'Kinapat',
            'Mabuhay',
            'Madaya',
            'Mendis',
            'Nabaliwa',
            'New Eden',
            'Poblacion',
            'Songco',
            'Sto. Niño',
        ],
        'Quezon' => [
            'Balidoyon',
            'Batangan',
            'Butong',
            'Caimpugan',
            'Cantugas',
            'Cebole',
            'Dungos',
            'Imbatug',
            'Kiara',
            'Kiburiao',
            'Kisawa',
            'Kitaihon',
            'Kibongkog',
            'Mabuhay',
            'Malabaogan',
            'Marapangi',
            'Miondow',
            'New Eden',
            'Panadtalan',
            'Pinamula',
            'Poblacion',
            'San Isidro',
            'San Jose',
            'San Roque',
            'Santo Niño',
            'Sinayawan',
            'Sinuda',
        ],
        'San Fernando' => [
            'Bagonggahon',
            'Barangay I (Pob.)',
            'Barangay II (Pob.)',
            'Barangay III (Pob.)',
            'Barangay IV (Pob.)',
            'Camboayon',
            'Casigpit',
            'Cawayan',
            'Collado',
            'Dagumbaan',
            'Halapitan',
            'Ilihan',
            'Kibogtok',
            'Kibongkog',
            'Kimanait',
            'Lagacan',
            'Lilingayon',
            'Magkalungay',
            'Mambago',
            'Olaycon',
            'Pagangan',
            'San Isidro',
            'San Jose',
            'San Roque',
            'Sudlon',
        ],
        'Sumilao' => [
            'Kisolon',
            'Lupiagan',
            'Ocasion',
            'Paminglang',
            'Panganan',
            'Poblacion',
            'San Roque',
            'San Vicente',
            'Vista Villa',
        ],
        'Talakag' => [
            'Barangay 1 (Pob.)',
            'Barangay 2 (Pob.)',
            'Barangay 3 (Pob.)',
            'Barangay 4 (Pob.)',
            'Barangay 5 (Pob.)',
            'Basak',
            'Boa',
            'Cacaon',
            'Dagumbaan',
            'Dominorog',
            'Indulang',
            'Lantud',
            'Lapu-lapu',
            'Liguron',
            'Luntian',
            'Miaray',
            'San Antonio',
            'San Isidro',
            'San Miguel',
            'San Roque',
            'Santo Niño',
            'Sto. Tomas',
            'Tumaras',
        ],
        'Valencia City' => [
            'Bagontaas',
            'Balatukan',
            'Banlag',
            'Barobo',
            'Batangan',
            'Catumbalon',
            'Colonia',
            'Concepcion',
            'Dagat-Kidavao',
            'Guinoyuran',
            'Gumpingan',
            'Laligan',
            'Lilingayon',
            'Lourdes',
            'Lumbayao',
            'Lumbo',
            'Mailag',
            'Malidong',
            'Nabago',
            'Pinatilan',
            'Poblacion',
            'San Carlos',
            'San Isidro',
            'Sinabuagan',
            'Sinayawan',
            'Sugod',
            'Tongantongan',
            'Vintar',
        ],
        'Malaybalay City' => [
            'Aglayan',
            'Barangay 1 (Pob.)',
            'Barangay 2 (Pob.)',
            'Barangay 3 (Pob.)',
            'Barangay 4 (Pob.)',
            'Barangay 5 (Pob.)',
            'Barangay 6 (Pob.)',
            'Barangay 7 (Pob.)',
            'Barangay 8 (Pob.)',
            'Barangay 9 (Pob.)',
            'Barangay 10 (Pob.)',
            'Barangay 11 (Pob.)',
            'Bangcud',
            'Busdi',
            'Cabangahan',
            'Caburacanan',
            'Can-ayan',
            'Casisang',
            'Dalwangan',
            'Imbayao',
            'Kalasungay',
            'Kapalong',
            'Kulaman',
            'Laguitas',
            'Linabo',
            'Magsaysay',
            'Managok',
            'Maraymaray',
            'Miglamin',
            'Patpat',
            'San Jose',
            'San Martin',
            'Santo Niño',
            'Siloo',
            'Simaya',
            'Sumpong',
            'Violacion',
            'Zamboanguita',
        ],
    ],
];

