<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Bukidnon Municipalities and Barangays
    |--------------------------------------------------------------------------
    |
    | This configuration file contains all municipalities in Bukidnon
    | and their respective barangays for the incident reporting system.
    |
    */

    'municipalities' => [
        'Baungon' => [
            'Balintad',
            'Buenavista',
            'Danatag',
            'Imbatug',
            'Kalilangan',
            'Lacolac',
            'Langaon',
            'Liboran',
            'Lingating',
            'Mabuhay',
            'Mabunga',
            'Nicdao',
            'Pualas',
            'Salimbalan',
            'San Miguel',
            'San Vincente',
        ],
        'Cabanglasan' => [
            'Anlogan',
            'Cabulohan',
            'Canangaan',
            'Dalacutan',
            'Freedom',
            'Iba',
            'Imbatug',
            'Jasaan',
            'Lambangan',
            'Mandahikan',
            'Mandaing',
            'Mauswagon',
            'Paradise',
            'Poblacion',
        ],
        'Damulog' => [
            'Aludas',
            'Angga-an',
            'Kinapat',
            'Kiraon',
            'Kitingting',
            'Lagandang',
            'Macapari',
            'Maican',
            'Migcawayan',
            'New Compostela',
            'Old Damulog',
            'Omonay',
            'Poblacion',
            'Pocopoco',
            'Sampagar',
            'San Isidro',
            'Tangkulan',
        ],
        'Dangcagan' => [
            'Barongcot',
            'Bugwak',
            'Dolorosa',
            'Kapalaran',
            'Kianggat',
            'Lourdes',
            'Macarthur',
            'Miaray',
            'Migcuya',
            'New Visayas',
            'Osmeña',
            'Poblacion',
            'Sagbayan',
            'San Vicente',
        ],
        'Don Carlos' => [
            'Bismartz',
            'Bocboc',
            'Buyot',
            'Cabadiangan',
            'Calaocalao',
            'Don Carlos Norte',
            'Don Carlos Sur',
            'Embayao',
            'Kalubihon',
            'Kasigkot',
            'Kawilihan',
            'Kiara',
            'Kibatang',
            'Mahayahay',
            'Manlamonay',
            'Maraymaray',
            'Mauswagon',
            'Minsalagan',
            'New Nongnongan',
            'New Visayas',
            'Old Nongnongan',
            'Pinamaloy',
            'Paualas',
            'San Antonio East',
            'San Antonio West',
            'San Francisco',
            'San Nicolas',
            'San Roque',
            'Sinangguyan',
        ],
        'Impasugong' => [
            'Bontongon',
            'Bulonay',
            'Captian Bayong',
            'Cawayan',
            'Dumalaguing',
            'Guihean',
            'Hagpa',
            'Impalutao',
            'Kalabugao',
            'Kibenton',
            'La Fortuna',
            'Poblacion',
            'Sayawan',
        ],
        'Kadingilan' => [
            'Bagongbayan',
            'Bagor',
            'Balaoro',
            'Baroy',
            'Cabadiangan',
            'Kibalagon',
            'Kibogtok',
            'Mabuhay',
            'Malinao',
            'Matampay',
            'Pay-as',
            'Pinamunguhan',
            'Poblacion',
            'Salvacion',
            'San Andres',
            'Sibonga',
        ],
        'Kalilangan' => [
            'Buyot',
            'Bangbang',
            'Canituan',
            'Kibaning',
            'Kinura',
            'Lampanusan',
            'Maca-opao',
            'Malinao',
            'Ninoy Aquino',
            'Pamotolon',
            'Poblacion',
            'Public',
            'San Vincente Ferrer',
            'West Poblacion',
        ],
        'Kibawe' => [
            'Balintawak',
            'Bukang Liwayway',
            'Cagawasan',
            'East Kibawe',
            'Gutapol',
            'Kiorao',
            'Kisawa',
            'Labuagon',
            'Magsaysay',
            'Marapangi',
            'Mascariñas',
            'Natulogan',
            'New Kidapawan',
            'Old Kibawe',
            'Palma',
            'Pinamula',
            'Romagooc',
            'Sampaguita',
            'Sanipon',
            'Spring',
            'Talahiron',
            'Tumaras',
            'West Kibawe',
        ],
        'Kitaotao' => [
            'Balangigay',
            'Balukbukan',
            'Bershiba',
            'Binoongan',
            'Bobong',
            'Bolocaon',
            'Cabalantian',
            'Calapaton',
            'Digongan',
            'East Dalurong',
            'Kahusayan',
            'Kalumihan',
            'Kauyonan',
            'Kimolong',
            'Kipilas',
            'Kitaihon',
            'Kitobo',
            'Kiulom',
            'Magsaysay',
            'Malobalo',
            'Metebagao',
            'Napalico',
            'Pagan',
            'Panganan',
            'Poblacion',
            'Sagundanon',
            'San Isidro',
            'San Lorenzo',
            'Santo Rosario',
            'Sinaysayan',
            'Sinuda',
            'Tandong',
            'Tawas',
            'West Dalurong',
            'White Kulaman',
        ],
        'Lantapan' => [
            'Alanib',
            'Baclayon',
            'Balila',
            'Bantuanon',
            'Basak',
            'Bugcaon',
            'Capitan Juan',
            'Cawayan',
            'Ka-atoan',
            'Kibangay',
            'Kulasihan',
            'Poblacion',
            'Songco',
            'Victory',
        ],
        'Libona' => [
            'Capihan',
            'Crossing',
            'Gango',
            'Kiliog',
            'Kinawe',
            'Laturan',
            'Maambong',
            'Nangka',
            'Poblacion',
            'Pongol',
            'San Jose',
            'Santa Fe',
            'Sil-ipon',
        ],
        'Malitbog' => [
            'Kalingking',
            'Kiabo',
            'Mindagat',
            'Omagling',
            'Patpat',
            'Poblacion',
            'Sampiano',
            'San Luis',
            'San Ines',
            'Silo-o',
            'Sumalsag',
        ],
        'Manolo Fortich' => [
            'Agusan Canyon',
            'Alae',
            'Dahilayan',
            'Dalirig',
            'Damilag',
            'Diclum',
            'Guilang-guilang',
            'Kalugmanan',
            'Lindaban',
            'Lingion',
            'Lingion',
            'Lunocan',
            'Maluko',
            'Mambatangan',
            'Mampayag',
            'Mantibugao',
            'Minsuro',
            'San Miguel',
            'Sankanan',
            'Santiago',
            'Santo Niño',
            'Tankulan',
            'Ticala',
        ],
        'Maramag' => [
            'Anahawon',
            'Bagong silang',
            'Base Camp',
            'Bayabason',
            'Camp I',
            'Colambugan',
            'Dagumba-an',
            'Danggawan',
            'Dologon',
            'Kiharong',
            'Kisanday',
            'Kuya',
            'La Roxas',
            'North Poblacion',
            'Panadtalan',
            'Panalsalan',
            'San Miguel',
            'San Roque',
            'South Poblacion',
            'Tubigon',
        ],
        'Pangantucan' => [
            'Adtuyon',
            'Bacusanon',
            'Bangahan',
            'Barandias',
            'Concepcion',
            'Gandingan',
            'Kimanait',
            'Kipadukan',
            'Langcataon',
            'Lantay',
            'Madaya',
            'Malipayon',
            'Mendis',
            'Nabaliwa',
            'New Eden',
            'Payad',
            'Pigtauranan',
            'Poblacion',
            'Portulin',
        ],
        // quezon municipality and its barangays
        'Quezon' => [
            'Butong',
            'Cawayan',
            'Cebole',
            'C-Handumanan',
            'Delapa',
            'Dumalama',
            'Kiburiao',
            'Kipaypayon',
            'Libertad',
            'Linabo',
            'Lipa',
            'Lumintao',
            'Magsaysay',
            'Mahayag',
            'Manuto',
            'Merangerang',
            'Mibantang',
            'Minongan',
            'Minsalirak',
            'Minsamongan',
            'Paitan',
            'Palacapao',
            'Pinilayan',
            'Poblacion',
            'Puntian',
            'Salawagan',
            'San Isidro',
            'San Jose',
            'San Roque',
            'Santa Cruz',
            'Santa Filomena',
        ],
        'San Fernando' => [
            'Bonacao',
            'Bulalang',
            'Cabuling',
            'Candelaria',
            'Cayaga',
            'Dao',
            'Durian',
            'Halapitan',
            'Iglugsad',
            'Kalagangan',
            'Kawayan',
            'Kibongcog',
            'Little Baguio',
            'Mabuhay',
            'Magkalungay',
            'Malayanan',
            'Matupe',
            'Nacabuklad',
            'Namnam',
            'Palacpacan',
            'Sacramento Valley',
            'San Jose',
            'Santo Domingo',
            'Tugop',
        ],
        'Sumilao' => [
            'Culasi',
            'Kisolon',
            'Licoan',
            'Lupiagan',
            'Ocasion',
            'Poblacion',
            'Puntian',
            'San Roque',
            'San Vicente',
            'Vista Villa',
        ],
        'Talakag' => [
            'Barangay 1',
            'Barangay 2',
            'Barangay 3',
            'Barangay 4',
            'Barangay 5',
            'Basak',
            'Baylanan',
            'Cacaon',
            'Cosina',
            'Dagumbaan',
            'Dagundalahon',
            'Dominorog',
            'Indulang',
            'Lantud',
            'Lapu-lapu',
            'Liguron',
            'Luntian',
            'Lantud',
            'Lapok',
            'Liguron',
            'Lingi-on',
            'Lirongan',
            'Miarayon',
            'Sagaran',
            'Salucot',
            'San Antonio',
            'San Isidro',
            'San Miguel',
            'San Rafael',
            'Santo Niño',
            'Tagbak',
            'Tikalaan',
        ],
        'Valencia City' => [
            'Bagontaas',
            'Banlag',
            'Barobo',
            'Batangan',
            'Catumbalon',
            'Colonia',
            'Concepcion',
            'Dagat-Kidavao',
            'Guinoyuran',
            'Kahapunan',
            'Laligan',
            'Lilingayon',
            'Lourdes',
            'Lumbayao',
            'Lumbo',
            'Lurogan',
            'Maapag',
            'Mabuhay',
            'Mailag',
            'Mt.Nebo',
            'Nabago',
            'Pinatilan',
            'Poblacion',
            'San Carlos',
            'San Isidro',
            'Sinabuagan',
            'Sinayawan',
            'Sugod',
            'Tongantongan',
            'Tugaya',
            'Vintar',
        ],
        'Malaybalay City' => [
            'Aglayan',
            'Apo Macote',
            'Bangcud',
            'Barangay 1',
            'Barangay 2',
            'Barangay 3',
            'Barangay 4',
            'Barangay 5',
            'Barangay 6',
            'Barangay 7',
            'Barangay 8',
            'Barangay 9',
            'Barangay 10',
            'Barangay 11',
            'Busdi',
            'Cabangahan',
            'Caburacanan',
            'Can-ayan',
            'Capitan Angel',
            'Casisang',
            'Dalwangan',
            'Indalaza',
            'Imbayao',
            'Kabalabag',
            'Kalasungay',
            'Kulaman',
            'Laguitas',
            'Linabo',
            'Magsaysay',
            'Maligaya',
            'Managok',
            'Manalog',
            'Mapayag',
            'Mapulo',
            'Miglamin',
            'Patpat',
            'Saint Peter',
            'San Jose',
            'San Martin',
            'Santo Niño',
            'Silae',
            'Simaya',
            'Sinanglanan',
            'Sumpong',
            'Violeta',
            'Zamboanguita',
        ],
    ],
];

